--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=3, microseconds=353549), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 451, 'message': 'Start to run testcase: request methods testcase: reference testcase, TestCase ID: 4170942c-259a-4064-abcc-7c98f316bb54', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 55, 924193, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=3, microseconds=355549), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: request with functions >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 55, 926193, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=3, microseconds=355549), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: get with params >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 55, 926193, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=602500), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 188, 'message': "failed to get client address info: 'WrappedSocket' object has no attribute 'getsockname'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 173144, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 183, in request
    client_ip, client_port = response.raw.connection.sock.getsockname()
AttributeError: 'WrappedSocket' object has no attribute 'getsockname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=604507), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 196, 'message': "failed to get server address info: 'WrappedSocket' object has no attribute 'getpeername'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 175151, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 191, in request
    server_ip, server_port = response.raw.connection.sock.getpeername()
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=607506), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : GET\nurl      : https://postman-echo.com/get?foo1=bar11&foo2=bar21&sum_v=3\nheaders  : {\n    "User-Agent": "HttpRunner/3.1.6",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "HRUN-Request-ID": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-555927"\n}\ncookies  : {}\nbody     : None\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 178150, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=608455), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Date": "Thu, 12 Aug 2021 07:15:57 GMT",\n    "Content-Type": "application/json; charset=utf-8",\n    "Content-Length": "421",\n    "Connection": "keep-alive",\n    "ETag": "W/\\"1a5-r1ii3JaThWMHBPbHSKGtlTsH0lQ\\"",\n    "Vary": "Accept-Encoding",\n    "set-cookie": "sails.sid=s%3AzqRirY1v-B3gntbUI7Wc2n1y2-8bRfju.iN%2BB2O1UyOTihgM9XAljYTd1wabGzlr4hsljxe9nzXQ; Path=/; HttpOnly"\n}\ncookies  : {\n    "sails.sid": "s%3AzqRirY1v-B3gntbUI7Wc2n1y2-8bRfju.iN%2BB2O1UyOTihgM9XAljYTd1wabGzlr4hsljxe9nzXQ"\n}\nencoding : utf-8\ncontent_type : application/json; charset=utf-8\nbody     : {\n    "args": {\n        "foo1": "bar11",\n        "foo2": "bar21",\n        "sum_v": "3"\n    },\n    "headers": {\n        "x-forwarded-proto": "https",\n        "x-forwarded-port": "443",\n        "host": "postman-echo.com",\n        "x-amzn-trace-id": "Root=1-6114caad-05f4837c3db590b8593d339e",\n        "user-agent": "HttpRunner/3.1.6",\n        "accept-encoding": "gzip, deflate",\n        "accept": "*/*",\n        "hrun-request-id": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-555927"\n    },\n    "url": "https://postman-echo.com/get?foo1=bar11&foo2=bar21&sum_v=3"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 179099, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=609455), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 218, 'message': 'status_code: 200, response_time(ms): 1245.95 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 180099, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=610456), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'extract', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 179, 'message': "extract mapping: {'foo3': 'bar21'}", 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 181100, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=611456), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 182100, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=612455), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.args.foo1 equal bar11(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 183099, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=612455), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.args.sum_v equal 3(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 183099, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=613454), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.args.foo2 equal bar21(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 184098, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=613454), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: get with params <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 184098, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=613454), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: post raw text >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 184098, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=934175), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 188, 'message': "failed to get client address info: 'WrappedSocket' object has no attribute 'getsockname'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 504819, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 183, in request
    client_ip, client_port = response.raw.connection.sock.getsockname()
AttributeError: 'WrappedSocket' object has no attribute 'getsockname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=936177), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 196, 'message': "failed to get server address info: 'WrappedSocket' object has no attribute 'getpeername'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 506821, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 191, in request
    server_ip, server_port = response.raw.connection.sock.getpeername()
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=937171), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : https://postman-echo.com/post\nheaders  : {\n    "User-Agent": "HttpRunner/3.1.6",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "Content-Type": "text/plain",\n    "HRUN-Request-ID": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-557185",\n    "Cookie": "sails.sid=s%3AzqRirY1v-B3gntbUI7Wc2n1y2-8bRfju.iN%2BB2O1UyOTihgM9XAljYTd1wabGzlr4hsljxe9nzXQ",\n    "Content-Length": "83"\n}\ncookies  : {\n    "sails.sid": "s%3AzqRirY1v-B3gntbUI7Wc2n1y2-8bRfju.iN%2BB2O1UyOTihgM9XAljYTd1wabGzlr4hsljxe9nzXQ"\n}\nbody     : This is expected to be sent back as part of response body: bar12-config_bar2-bar32.\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 507815, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=939201), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Date": "Thu, 12 Aug 2021 07:15:57 GMT",\n    "Content-Type": "application/json; charset=utf-8",\n    "Content-Length": "631",\n    "Connection": "keep-alive",\n    "ETag": "W/\\"277-30M5AInW3nOPKIy52d9RIV9WbkQ\\"",\n    "Vary": "Accept-Encoding",\n    "set-cookie": "sails.sid=s%3A6GgJys_msE1cRSEcF1rzhWi0U7FJaS9q.0hg46B8rAY%2B%2BHO2GS5Tb%2FB28WbSeYTzD5jMrcwbcxYs; Path=/; HttpOnly"\n}\ncookies  : {\n    "sails.sid": "s%3A6GgJys_msE1cRSEcF1rzhWi0U7FJaS9q.0hg46B8rAY%2B%2BHO2GS5Tb%2FB28WbSeYTzD5jMrcwbcxYs"\n}\nencoding : utf-8\ncontent_type : application/json; charset=utf-8\nbody     : {\n    "args": {},\n    "data": "This is expected to be sent back as part of response body: bar12-config_bar2-bar32.",\n    "files": {},\n    "form": {},\n    "headers": {\n        "x-forwarded-proto": "https",\n        "x-forwarded-port": "443",\n        "host": "postman-echo.com",\n        "x-amzn-trace-id": "Root=1-6114caad-179bee391f6708813e8196c7",\n        "content-length": "83",\n        "user-agent": "HttpRunner/3.1.6",\n        "accept-encoding": "gzip, deflate",\n        "accept": "*/*",\n        "content-type": "text/plain",\n        "hrun-request-id": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-557185",\n        "cookie": "sails.sid=s%3AzqRirY1v-B3gntbUI7Wc2n1y2-8bRfju.iN%2BB2O1UyOTihgM9XAljYTd1wabGzlr4hsljxe9nzXQ"\n    },\n    "json": null,\n    "url": "https://postman-echo.com/post"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 509845, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=939201), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 218, 'message': 'status_code: 200, response_time(ms): 319.72 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 509845, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=939201), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 509845, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=940175), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.data equal This is expected to be sent back as part of response body: bar12-config_bar2-bar32.(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 510819, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=940175), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: post raw text <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 510819, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=941165), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: post form data >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 511809, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=254506), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 188, 'message': "failed to get client address info: 'WrappedSocket' object has no attribute 'getsockname'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 825150, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 183, in request
    client_ip, client_port = response.raw.connection.sock.getsockname()
AttributeError: 'WrappedSocket' object has no attribute 'getsockname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=256506), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 196, 'message': "failed to get server address info: 'WrappedSocket' object has no attribute 'getpeername'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 827150, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 191, in request
    server_ip, server_port = response.raw.connection.sock.getpeername()
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=257507), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : https://postman-echo.com/post\nheaders  : {\n    "User-Agent": "HttpRunner/3.1.6",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "Content-Type": "application/x-www-form-urlencoded",\n    "HRUN-Request-ID": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-557511",\n    "Cookie": "sails.sid=s%3A6GgJys_msE1cRSEcF1rzhWi0U7FJaS9q.0hg46B8rAY%2B%2BHO2GS5Tb%2FB28WbSeYTzD5jMrcwbcxYs",\n    "Content-Length": "44"\n}\ncookies  : {\n    "sails.sid": "s%3A6GgJys_msE1cRSEcF1rzhWi0U7FJaS9q.0hg46B8rAY%2B%2BHO2GS5Tb%2FB28WbSeYTzD5jMrcwbcxYs"\n}\nbody     : foo1=testcase_ref_bar1&foo2=bar23&foo3=bar21\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 828151, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=258499), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Date": "Thu, 12 Aug 2021 07:15:57 GMT",\n    "Content-Type": "application/json; charset=utf-8",\n    "Content-Length": "685",\n    "Connection": "keep-alive",\n    "ETag": "W/\\"2ad-EjyP/sOEPnDLmpsiqzLkNXT8prE\\"",\n    "Vary": "Accept-Encoding",\n    "set-cookie": "sails.sid=s%3AJsoWYNULY3SL0S4HhOZZI5b686hjLy8r.FxpRJDrg3cjA6PkesD1ODygGyF9kNmPcKcDiswLey7g; Path=/; HttpOnly"\n}\ncookies  : {\n    "sails.sid": "s%3AJsoWYNULY3SL0S4HhOZZI5b686hjLy8r.FxpRJDrg3cjA6PkesD1ODygGyF9kNmPcKcDiswLey7g"\n}\nencoding : utf-8\ncontent_type : application/json; charset=utf-8\nbody     : {\n    "args": {},\n    "data": "",\n    "files": {},\n    "form": {\n        "foo1": "testcase_ref_bar1",\n        "foo2": "bar23",\n        "foo3": "bar21"\n    },\n    "headers": {\n        "x-forwarded-proto": "https",\n        "x-forwarded-port": "443",\n        "host": "postman-echo.com",\n        "x-amzn-trace-id": "Root=1-6114caad-301f5d8c70c41891391e360c",\n        "content-length": "44",\n        "user-agent": "HttpRunner/3.1.6",\n        "accept-encoding": "gzip, deflate",\n        "accept": "*/*",\n        "content-type": "application/x-www-form-urlencoded",\n        "hrun-request-id": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-557511",\n        "cookie": "sails.sid=s%3A6GgJys_msE1cRSEcF1rzhWi0U7FJaS9q.0hg46B8rAY%2B%2BHO2GS5Tb%2FB28WbSeYTzD5jMrcwbcxYs"\n    },\n    "json": {\n        "foo1": "testcase_ref_bar1",\n        "foo2": "bar23",\n        "foo3": "bar21"\n    },\n    "url": "https://postman-echo.com/post"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 829143, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=258499), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 218, 'message': 'status_code: 200, response_time(ms): 313.34 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 829143, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=259529), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 830173, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=259529), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.form.foo1 equal testcase_ref_bar1(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 830173, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=259529), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.form.foo2 equal bar23(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 830173, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=260506), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.form.foo3 equal bar21(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 831150, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=260506), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: post form data <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 831150, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=261503), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step_testcase', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 286, 'message': "export variables: {'foo3': 'bar21'}", 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 832147, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=261503), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: request with functions <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 832147, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=261503), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: post form data >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 57, 832147, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=573482), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 188, 'message': "failed to get client address info: 'WrappedSocket' object has no attribute 'getsockname'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 144126, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 183, in request
    client_ip, client_port = response.raw.connection.sock.getsockname()
AttributeError: 'WrappedSocket' object has no attribute 'getsockname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=575497), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='WARNING', no=30, icon='‚ö†Ô∏è'), 'line': 196, 'message': "failed to get server address info: 'WrappedSocket' object has no attribute 'getpeername'", 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 146141, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "D:\my_github\python_about\new_httprunner3\httprunner\client.py", line 191, in request
    server_ip, server_port = response.raw.connection.sock.getpeername()
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=577473), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : https://postman-echo.com/post\nheaders  : {\n    "User-Agent": "HttpRunner/3.1.6",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "Content-Type": "application/x-www-form-urlencoded",\n    "HRUN-Request-ID": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-557833",\n    "Cookie": "sails.sid=s%3AJsoWYNULY3SL0S4HhOZZI5b686hjLy8r.FxpRJDrg3cjA6PkesD1ODygGyF9kNmPcKcDiswLey7g",\n    "Content-Length": "20"\n}\ncookies  : {\n    "sails.sid": "s%3AJsoWYNULY3SL0S4HhOZZI5b686hjLy8r.FxpRJDrg3cjA6PkesD1ODygGyF9kNmPcKcDiswLey7g"\n}\nbody     : foo1=bar1&foo2=bar21\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 148117, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=578520), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Date": "Thu, 12 Aug 2021 07:15:58 GMT",\n    "Content-Type": "application/json; charset=utf-8",\n    "Content-Length": "623",\n    "Connection": "keep-alive",\n    "ETag": "W/\\"26f-CGJQW8Rw+9vOr+5ajHiHXk1/tEI\\"",\n    "Vary": "Accept-Encoding",\n    "set-cookie": "sails.sid=s%3AFzlZdoV0IQ-lXhvN-IdbdzSaALKYrB3L.iRqERy2G9%2BS3vQJrcZ1x%2B52xrxmVYs5C8nEEoQ9jNH8; Path=/; HttpOnly"\n}\ncookies  : {\n    "sails.sid": "s%3AFzlZdoV0IQ-lXhvN-IdbdzSaALKYrB3L.iRqERy2G9%2BS3vQJrcZ1x%2B52xrxmVYs5C8nEEoQ9jNH8"\n}\nencoding : utf-8\ncontent_type : application/json; charset=utf-8\nbody     : {\n    "args": {},\n    "data": "",\n    "files": {},\n    "form": {\n        "foo1": "bar1",\n        "foo2": "bar21"\n    },\n    "headers": {\n        "x-forwarded-proto": "https",\n        "x-forwarded-port": "443",\n        "host": "postman-echo.com",\n        "x-amzn-trace-id": "Root=1-6114caae-67c29c306e6412102935c0d0",\n        "content-length": "20",\n        "user-agent": "HttpRunner/3.1.6",\n        "accept-encoding": "gzip, deflate",\n        "accept": "*/*",\n        "content-type": "application/x-www-form-urlencoded",\n        "hrun-request-id": "HRUN-4170942c-259a-4064-abcc-7c98f316bb54-557833",\n        "cookie": "sails.sid=s%3AJsoWYNULY3SL0S4HhOZZI5b686hjLy8r.FxpRJDrg3cjA6PkesD1ODygGyF9kNmPcKcDiswLey7g"\n    },\n    "json": {\n        "foo1": "bar1",\n        "foo2": "bar21"\n    },\n    "url": "https://postman-echo.com/post"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 149164, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=578520), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 218, 'message': 'status_code: 200, response_time(ms): 310.97 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 149164, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=579468), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 150112, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=579468), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.form.foo1 equal bar1(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 150112, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=580470), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 249, 'message': 'assert body.form.foo2 equal bar21(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 151114, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=580470), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: post form data <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 151114, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=580470), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\my_github\\python_about\\new_httprunner3\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 460, 'message': 'generate testcase log: D:\\my_github\\python_about\\new_httprunner3\\tt01\\logs\\4170942c-259a-4064-abcc-7c98f316bb54.run.log', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=7672, name='MainProcess'), 'thread': (id=3880, name='MainThread'), 'time': datetime(2021, 8, 12, 15, 15, 58, 151114, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '√ñ√ê¬π√∫¬±√™√ó¬º√ä¬±¬º√§'))}
Traceback (most recent call last):
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\gskyf\AppData\Local\Programs\Python\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
